version: '3.7'

services:
  postgres:
    container_name: postgres_db
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    networks:
      - node-bridge-network

networks:
  socket-network:
  node-bridge-network:
    driver: bridge
volumes:
  socket-pgdata:
